import = ["/home/pawel/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 0
