window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack Nerd Font
    style: Medium
  size: 12.0

import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
