require('options')
require('plugins')
require('keymaps')
-- require("colorscheme")
require("completion")
-- require("lsp")
require("telescope-config")
-- require("dap-config")
-- require("treesitter-config")
-- require("colorizer").setup()
