require('options')
require('lazy-init')
require('keymaps')
-- require("colorscheme")
require("completion")
require("lsp")
require("telescope-config")
require("treesitter-config")
-- require("colorizer").setup()
