#
# ~/.bashrc
#
# Dla odpalania go programików
export PATH=$PATH:/home/pawel/go/bin
# Musi być aby j działało
eval "$(jump shell)"

# Dla mozliwosci pozniej ssh-add
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 12h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim='nvim'
alias r='ranger'
PS1='[\u@\h \W]\$ '
