#
# ~/.bashrc
#

# Jeżeli shell jest non-interactive od razu wyjdź.
# Na przykład przy cron jobach, skryptach odpalanych przez servicy etc.
[[ $- != *i* ]] && return

# dla sudoedit
export EDITOR='nvim'
# Dla odpalania go programików
export PATH=$PATH:/home/pawel/go/bin
# For pipx
export PATH=$PATH:/home/pawel/.local/bin
# Musi być aby j działało
eval "$(jump shell)"

HISTSIZE=10000
HISTFILESIZE=200000
HISTTIMEFORMAT="%d/%m/%y %T "

# Dla mozliwosci pozniej ssh-add
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 12h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim='nvim'
alias r='ranger'
PS1='[\u@\h \W]\$ '
alias tn='tmux new -s $(pwd | sed "s/.*\///g")'
alias e='exit'

# for gpg commit signing
export GPG_TTY=$(tty)

# for pyenv
export PYENV_ROOT="$HOME/.pyenv"
eval "$(pyenv init -)"

# Po to aby zaciagał completion z customowego folderu.
if [ -d ~/.bash_completion.d ]; then
  for file in ~/.bash_completion.d/*; do
    [ -f "$file" ] && . "$file"
  done
fi
